basePath: /api
definitions:
  handlers.Character:
    properties:
      char:
        example: dʒ
        type: string
      confidence:
        example: 0.9997
        type: number
      end_offset:
        example: 0.24
        type: number
      start_offset:
        example: 0.16
        type: number
    type: object
  handlers.ResponsePhoneme:
    properties:
      characters:
        items:
          $ref: '#/definitions/handlers.Character'
        type: array
      confident:
        example: 0.92
        type: number
      ground_truth_benchmark:
        example: ˈrʌ[ˌ]baʊt dʒi ɛm i ɛf θri naɪn
        type: string
      predict:
        example: ˈrʌbaʊt dʒi ɛm i ɛf θri naɪn
        type: string
    type: object
  models.Image:
    properties:
      metadata:
        additionalProperties: true
        type: object
      name:
        type: string
      path:
        type: string
      size_in_bytes:
        type: integer
      thumbnail_url:
        type: string
      url:
        type: string
    type: object
  models.InternalError:
    properties:
      details:
        type: string
      message:
        type: string
      status:
        type: integer
      type:
        type: string
    type: object
  models.Lesson:
    properties:
      created_at:
        type: string
      ipa:
        type: string
      practice_items:
        items:
          $ref: '#/definitions/models.PracticeItem'
        type: array
      type:
        $ref: '#/definitions/models.LessonType'
    type: object
  models.LessonType:
    enum:
    - word
    - phrase
    - sentence
    - conversation
    type: string
    x-enum-varnames:
    - WordType
    - PhraseType
    - SentenceType
    - ConversationType
  models.PaginationMeta:
    properties:
      current_page:
        type: integer
      page_count:
        type: integer
      total_count:
        type: integer
    type: object
  models.PaginationWrapper:
    properties:
      data:
        type: object
      metadata:
        $ref: '#/definitions/models.PaginationMeta'
    type: object
  models.PracticeItem:
    properties:
      audio_url:
        type: string
      content:
        type: string
      transcript_ipa:
        type: string
      translation:
        type: string
    type: object
  models.Story:
    properties:
      audio_url:
        type: string
      author:
        type: string
      description:
        type: string
      duration:
        type: integer
      image_url:
        type: string
      source:
        type: string
      title:
        type: string
      transcription:
        type: string
      translation:
        type: string
      views:
        type: integer
    type: object
  models.StoryLevel:
    enum:
    - beginner
    - intermediate
    - advanced
    - proficient
    type: string
    x-enum-varnames:
    - Beginner
    - Intermediate
    - Advanced
    - Proficient
  models.StoryStatus:
    enum:
    - in_progress
    - completed
    type: string
    x-enum-varnames:
    - InProgress
    - Completed
  models.User:
    properties:
      avatar:
        type: string
      email:
        type: string
      lessons:
        description: relations
        items:
          $ref: '#/definitions/models.Lesson'
        type: array
      name:
        type: string
      stories:
        items:
          $ref: '#/definitions/models.Story'
        type: array
    required:
    - email
    type: object
  models.UserCredentials:
    properties:
      email:
        type: string
      password:
        minLength: 6
        type: string
    required:
    - email
    - password
    type: object
  models.UserDictionaries:
    properties:
      vocabulary_id:
        type: string
    type: object
  models.UserLesson:
    properties:
      lesson:
        $ref: '#/definitions/models.Lesson'
      lesson_id:
        type: string
      score:
        type: number
      user:
        $ref: '#/definitions/models.User'
      user_id:
        type: string
    type: object
  models.UserStory:
    properties:
      level:
        $ref: '#/definitions/models.StoryLevel'
      score:
        type: integer
      sentences:
        description: list sentences include vtt
        items:
          $ref: '#/definitions/models.UserStorySentence'
        type: array
      status:
        $ref: '#/definitions/models.StoryStatus'
      story:
        $ref: '#/definitions/models.Story'
      story_id:
        type: string
      user:
        $ref: '#/definitions/models.User'
      user_id:
        type: string
    required:
    - level
    type: object
  models.UserStorySentence:
    properties:
      content:
        type: string
      end:
        type: number
      start:
        type: number
      user_answers:
        items:
          type: string
        type: array
    type: object
  models.ValidationError:
    properties:
      details:
        type: string
      message:
        type: string
      status:
        type: integer
      type:
        type: string
      validation_errors:
        items:
          additionalProperties:
            type: string
          type: object
        type: array
    type: object
host: localhost:9000
info:
  contact: {}
  title: Swagger Boilerplate API
  version: "1.0"
paths:
  /application/heartbeat:
    get:
      responses:
        "200":
          description: OK
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.InternalError'
      summary: return a status
      tags:
      - heartbeat
  /auth/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: user
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.UserCredentials'
      responses:
        "200":
          description: OK
        "401":
          description: wrong username or password
          schema:
            $ref: '#/definitions/models.InternalError'
        "422":
          description: error validating
          schema:
            $ref: '#/definitions/models.ValidationError'
      security:
      - Bearer: []
      summary: login user
      tags:
      - auth
  /auth/logout:
    post:
      consumes:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: invalid refresh_token
          schema:
            $ref: '#/definitions/models.InternalError'
      security:
      - Bearer: []
      summary: logout current account
      tags:
      - auth
  /auth/refresh_token:
    post:
      consumes:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: invalid refresh_token
          schema:
            $ref: '#/definitions/models.InternalError'
      security:
      - Bearer: []
      summary: refresh token
      tags:
      - auth
  /auth/register:
    post:
      consumes:
      - application/json
      parameters:
      - description: user
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.UserCredentials'
      responses:
        "200":
          description: OK
        "400":
          description: duplicate email
          schema:
            $ref: '#/definitions/models.InternalError'
        "422":
          description: error validating
          schema:
            $ref: '#/definitions/models.ValidationError'
      summary: create a user
      tags:
      - auth
  /check-phonemes:
    post:
      consumes:
      - multipart/form-data
      parameters:
      - description: Audio file to upload
        in: formData
        name: audio_file
        required: true
        type: file
      - description: ground_truth
        in: formData
        name: ground_truth
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.ResponsePhoneme'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.InternalError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.InternalError'
      summary: upload an audio with phoneme
      tags:
      - phonemes
  /errors/{id}:
    get:
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.InternalError'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ValidationError'
      security:
      - Bearer: []
      summary: return an error
      tags:
      - errors
  /images:
    post:
      consumes:
      - multipart/form-data
      parameters:
      - description: Image file to upload
        in: formData
        name: image_file
        required: true
        type: file
      - description: Thumbnail image file to upload
        in: formData
        name: image_thumbnail_file
        required: true
        type: file
      - description: Metadata associated with the image
        in: formData
        name: metadata
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Image'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ValidationError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.InternalError'
      summary: upload an image with thumbnail
      tags:
      - images
  /lessons:
    get:
      parameters:
      - description: limit
        in: query
        name: limit
        type: string
      - description: page_number
        in: query
        name: page_number
        type: string
      - description: type
        in: query
        name: type
        type: string
      - description: name
        in: query
        name: name
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.PaginationWrapper'
        "404":
          description: Entity Not Found
          schema:
            $ref: '#/definitions/models.InternalError'
      security:
      - Bearer: []
      summary: return list lessons
      tags:
      - lessons
  /lessons/ipa:
    get:
      responses:
        "200":
          description: OK
      security:
      - Bearer: []
      summary: return list IPA
      tags:
      - lessons
  /users:
    get:
      parameters:
      - description: limit
        in: query
        name: limit
        type: string
      - description: page_number
        in: query
        name: page_number
        type: string
      - description: search_query
        in: query
        name: search_query
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.PaginationWrapper'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.InternalError'
      security:
      - Bearer: []
      summary: return list users
      tags:
      - users
  /users/{user_id}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: user_id
        in: path
        name: user_id
        required: true
        type: string
      responses:
        "200":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.InternalError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.InternalError'
      security:
      - Bearer: []
      summary: delete a user
      tags:
      - users
    get:
      parameters:
      - description: user_id
        in: path
        name: user_id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.InternalError'
      security:
      - Bearer: []
      summary: return a user
      tags:
      - users
    put:
      consumes:
      - application/json
      parameters:
      - description: user_id
        in: path
        name: user_id
        required: true
        type: string
      - description: user
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.User'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ValidationError'
        "404":
          description: Entity Not Found
          schema:
            $ref: '#/definitions/models.InternalError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.InternalError'
      security:
      - Bearer: []
      summary: update a user
      tags:
      - users
  /users/{user_id}/dictionaries:
    post:
      consumes:
      - application/json
      parameters:
      - description: User ID
        in: path
        name: user_id
        required: true
        type: string
      - description: dictionaries
        in: body
        name: dictionaries
        required: true
        schema:
          $ref: '#/definitions/models.UserDictionaries'
      responses:
        "200":
          description: OK
      security:
      - Bearer: []
      summary: add vocabulary in dictionary
      tags:
      - users
  /users/{user_id}/dictionaries/{vocabulary_id}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: user id
        in: path
        name: user_id
        required: true
        type: string
      - description: vocabulary id
        in: path
        name: vocabulary_id
        required: true
        type: string
      responses:
        "200":
          description: OK
      security:
      - Bearer: []
      summary: delete dictionary
      tags:
      - users
  /users/{user_id}/lessons:
    post:
      consumes:
      - application/json
      parameters:
      - description: User ID
        in: path
        name: user_id
        required: true
        type: string
      - description: Lesson
        in: body
        name: story
        required: true
        schema:
          $ref: '#/definitions/models.UserLesson'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.UserLesson'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ValidationError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.InternalError'
      security:
      - Bearer: []
      summary: create or update score lesson
      tags:
      - users
  /users/{user_id}/stories:
    post:
      consumes:
      - application/json
      parameters:
      - description: User ID
        in: path
        name: user_id
        required: true
        type: string
      - description: Story
        in: body
        name: story
        required: true
        schema:
          $ref: '#/definitions/models.UserStory'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.UserStory'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ValidationError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.InternalError'
      security:
      - Bearer: []
      summary: doing a story
      tags:
      - users
  /vocabularies:
    get:
      description: Retrieve vocabulary entries that match the provided word.
      parameters:
      - description: limit
        in: query
        name: limit
        type: string
      - description: page_number
        in: query
        name: page_number
        type: string
      - description: 'Ex: Personal Traits'
        in: query
        name: topic
        type: string
      - description: 'Ex: A1'
        in: query
        name: level
        type: string
      - description: 'Ex: persistent'
        in: query
        name: text
        type: string
      - description: is_strict = true return only one match
        in: query
        name: is_strict
        type: boolean
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.PaginationWrapper'
        "404":
          description: Entity Not Found
          schema:
            $ref: '#/definitions/models.InternalError'
      security:
      - Bearer: []
      summary: Search vocabularies by word
      tags:
      - vocabularies
securityDefinitions:
  Bearer:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
