basePath: /api
definitions:
  gin.H:
    additionalProperties: {}
    type: object
  models.Image:
    properties:
      metadata:
        additionalProperties: true
        type: object
      name:
        type: string
      path:
        type: string
      size_in_bytes:
        type: integer
      thumbnail_url:
        type: string
      url:
        type: string
    type: object
  models.User:
    properties:
      avatar:
        type: string
      email:
        type: string
      google_id:
        type: string
      is_pay:
        type: boolean
      username:
        type: string
    required:
    - email
    - username
    type: object
  models.UserCredentials:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  models.Vocabulary:
    properties:
      audio_url:
        type: string
      text:
        type: string
      transcript_ipa:
        type: string
      translation:
        type: string
    type: object
host: localhost:9000
info:
  contact: {}
  title: Swagger Boilerplate API
  version: "1.0"
paths:
  /application/heartbeat:
    get:
      responses:
        "200":
          description: OK
      summary: return a status
      tags:
      - heartbeat
  /auth/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: user
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.UserCredentials'
      responses:
        "200":
          description: OK
      security:
      - Bearer: []
      summary: login user
      tags:
      - auth
  /auth/register:
    post:
      consumes:
      - application/json
      parameters:
      - description: user
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.User'
      responses:
        "200":
          description: OK
      summary: create a user
      tags:
      - auth
  /errors/{id}:
    get:
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
      security:
      - Bearer: []
      summary: return a error
      tags:
      - errors
  /images:
    post:
      consumes:
      - multipart/form-data
      parameters:
      - description: Image file to upload
        in: formData
        name: image_file
        required: true
        type: file
      - description: Thumbnail image file to upload
        in: formData
        name: image_thumbnail_file
        required: true
        type: file
      - description: Metadata associated with the image
        in: formData
        name: metadata
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Image'
        "400":
          description: 'Bad Request: Validation Error'
          schema:
            $ref: '#/definitions/gin.H'
        "500":
          description: 'Internal Server Error: Could not save file or database error'
          schema:
            $ref: '#/definitions/gin.H'
      summary: upload an image with thumbnail
      tags:
      - images
  /users:
    get:
      parameters:
      - description: limit
        in: query
        name: limit
        type: string
      - description: page_number
        in: query
        name: page_number
        type: string
      - description: search_query
        in: query
        name: search_query
        type: string
      responses:
        "200":
          description: OK
      security:
      - Bearer: []
      summary: return list users
      tags:
      - users
  /users/{user_id}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: user_id
        in: path
        name: user_id
        required: true
        type: string
      responses:
        "200":
          description: OK
      security:
      - Bearer: []
      summary: delete a user
      tags:
      - users
    get:
      parameters:
      - description: user_id
        in: path
        name: user_id
        required: true
        type: string
      responses:
        "200":
          description: OK
      security:
      - Bearer: []
      summary: return a user
      tags:
      - users
    put:
      consumes:
      - application/json
      parameters:
      - description: user_id
        in: path
        name: user_id
        required: true
        type: string
      - description: user
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.User'
      responses:
        "200":
          description: OK
      security:
      - Bearer: []
      summary: update a user
      tags:
      - users
  /vocabularies/detail/{id}:
    get:
      consumes:
      - application/json
      description: Retrieves the vocabulary entry that matches the specified word
        or phrase.
      parameters:
      - description: Vocabulary term to search for
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Vocabulary details for the matching term
          schema:
            $ref: '#/definitions/models.Vocabulary'
      summary: Fetch vocabulary details
      tags:
      - vocabularies
  /vocabularies/search:
    get:
      consumes:
      - application/json
      description: Retrieve vocabulary entries that match the provided word.
      parameters:
      - description: The vocabulary word to search for
        in: query
        name: word
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: List of matching vocabulary entries
          schema:
            items:
              $ref: '#/definitions/models.Vocabulary'
            type: array
      summary: Search vocabularies by word
      tags:
      - vocabularies
securityDefinitions:
  Bearer:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
