CREATE TABLE errors
(
    id         INTEGER     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status     NUMERIC     NOT NULL,
    code       TEXT        NOT NULL,
    message    TEXT        NOT NULL,
    details    TEXT        NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
